---
title: "infeasibility-exploration"
output: pdf_document
date: "2023-08-09"
---

```{r}
cropland1 <- read_csv("../data/formatted-data/linear_constraints/nuts_crop_high_55.csv")
cropland2 <- read_csv("../data/formatted-data/linear_constraints/nuts_crop_med_55.csv")
cropland3 <- read_csv("../data/formatted-data/linear_constraints/nuts_crop_low_55.csv")
pasture1 <- read_csv("../data/formatted-data/linear_constraints/nuts_pasture_high_55.csv")
pasture2 <- read_csv("../data/formatted-data/linear_constraints/nuts_pasture_low_55.csv")
forestry1 <- read_csv("../data/formatted-data/linear_constraints/nuts_forest_multi_55.csv")
forestry2 <- read_csv("../data/formatted-data/linear_constraints/nuts_forest_prod_55.csv")
forestry3 <- read_csv("../data/formatted-data/linear_constraints/nuts_forest_pri_55.csv")
```

```{r}
nuts2_shp <- st_read("../data/EU_NUTS2_GLOBIOM/EU_GLOBIOM_NUTS2.shp") |>
  mutate(country = substr(NUTS2, start = 1, stop = 2))
nuts2_all <- nuts2_shp |>
  rename(NUTS_ID = NURGCDL2) |>
  mutate(nuts2id = seq(1:260)) |> dplyr::select(NUTS_ID, nuts2id)

pu_in_EU <- read_csv("../data/formatted-data/pu_in_EU.csv")

nuts_PU <- pu_in_EU |>
  left_join(as_tibble(nuts2_all)) |>
  group_by(NUTS_ID) |>
  count()  |> arrange(n)

zones <- read_csv("../data/formatted-data/zone_id.csv") |>
  mutate(name = paste0("z", id))

manual_bounded_constraints <- read_csv("../data/formatted-data/manual_bounded_constraints_production_globiom_flex.csv") |>
  left_join(zones) |>
  dplyr::select(pu, zone, lower, upper, nuts2id)

n2k_nuts2 <- manual_bounded_constraints |>   
  left_join(as_tibble(nuts2_all)) |> 
  dplyr::select(-geometry) |>
  separate(zone, c('maes_label', 'intensity', 'action'), sep = "_") |>
  filter(action == "conserve" | maes_label == "Urban") |>
  group_by(NUTS_ID) |> 
  summarise(n2k = sum(lower))

conflict_nuts <- cropland1 |> dplyr::select(NUTS_ID, name, value) |>
  rbind(cropland2, cropland3,
        pasture1, pasture2, 
        forestry1, forestry2) |>
  group_by(NUTS_ID) |>
  summarise(value = sum(value)/10) |>
  left_join(nuts_PU) |>
  mutate(perc_prod = value/n*100) |>
  arrange(-perc_prod) |>
  left_join(n2k_nuts2) |>
  mutate(conflict = n-(value + n2k)) |>
  arrange(conflict) |>
  filter(conflict < 0) |>
  dplyr::select(c(NUTS_ID, conflict))

conflict_nuts |> arrange(NUTS_ID)
```


```{r}

```

